"""Stable base with users

Revision ID: 10af6f0618f5
Revises: 
Create Date: 2026-01-30 10:39:25.450215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10af6f0618f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charities'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('image_file', sa.String(length=100), nullable=True),
    sa.Column('times_worn', sa.Integer(), nullable=True),
    sa.Column('celeb_twin', sa.String(length=100), nullable=True),
    sa.Column('styling_tip', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clothing_items_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clothing_items'))
    )
    op.create_table('donation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('charity_name', sa.String(length=100), nullable=True),
    sa.Column('date_donated', sa.DateTime(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_donation_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_records'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation_records')
    op.drop_table('clothing_items')
    op.drop_table('users')
    op.drop_table('charities')
    # ### end Alembic commands ###
